#!/usr/bin/env python3
"""
serial-proteins.py

Single-process (serial) solution for Lab2.

What it does:
1) Reads a CSV dataset generated by `proteins-generator.py` (columns: protid, enzyme, hydrofob, sequence).
2) Asks the user for a pattern (substring) and converts it to UPPERCASE.
3) Measures wall-clock time for the search.
4) Counts overlapping occurrences of the pattern in every protein sequence.
5) Keeps only proteins with >0 matches.
6) Prints the runtime and the winning protein ID:
      - winner = protein with the MAX number of matches;
      - ties are broken by the MAX hydrofob.
7) Builds a bar chart for TOP-10 by matches and annotates the bar that has the
   maximum hydrofob among those TOP-10.
8) Saves the chart to 'top10_matches.png' in the same folder.

Run:
  python serial-proteins.py
  (Working directory must contain 'proteins.csv')

Dependencies (install once in your venv):
  pip install pandas matplotlib
"""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import Tuple

import pandas as pd
import matplotlib.pyplot as plt


# ---------- Utility functions ----------

def count_overlapping(haystack: str, needle: str) -> int:
    """
    Count overlapping occurrences of `needle` in `haystack`.

    Example:
      haystack="AAAA", needle="AA"  -> 3 (positions 0-1, 1-2, 2-3)

    We use a simple sliding scan; Python's str.count() does NOT count overlaps,
    so we cannot use it here.
    """
    if not needle:
        return 0
    n, m = len(haystack), len(needle)
    if m > n:
        return 0

    count = 0
    # Slide a window of length m across the string and compare slices
    for i in range(0, n - m + 1):
        if haystack[i:i + m] == needle:
            count += 1
    return count


def load_dataset(csv_path: Path) -> pd.DataFrame:
    """
    Load the dataset and normalize text columns to UPPERCASE where appropriate.

    Expected columns:
      - protid (string/integer-like id)
      - enzyme (string code, not used in logic but kept)
      - hydrofob (numeric)
      - sequence (protein sequence, uppercase letters)

    If the file is missing, we fail with a clear message.
    """
    if not csv_path.exists():
        sys.exit(f"[ERROR] CSV not found: {csv_path}. "
                 f"Generate it first with: python proteins-generator.py 50000")

    df = pd.read_csv(csv_path, dtype={"protid": str})
    # Robustness: ensure required columns exist
    required_cols = {"protid", "enzyme", "hydrofob", "sequence"}
    missing = required_cols - set(df.columns)
    if missing:
        sys.exit(f"[ERROR] CSV missing columns: {missing}. "
                 f"Got {list(df.columns)}")

    # Normalize case for string columns we use in matching
    df["sequence"] = df["sequence"].astype(str).str.upper()
    df["enzyme"] = df["enzyme"].astype(str).str.upper()
    # hydrofob should be numeric
    df["hydrofob"] = pd.to_numeric(df["hydrofob"], errors="coerce").fillna(0)

    return df


def pick_winner(df_matches: pd.DataFrame) -> Tuple[str, int, float]:
    """
    Given a dataframe with columns: protid, matches, hydrofob
    return the winner according to:
      - max(matches)
      - tie-breaker: max(hydrofob)

    Returns: (protid, matches, hydrofob)
    """
    if df_matches.empty:
        return ("", 0, 0.0)

    # Sort by matches desc, hydrofob desc; take the first row
    ordered = df_matches.sort_values(
        by=["matches", "hydrofob"], ascending=[False, False]
    )
    row = ordered.iloc[0]
    return (str(row["protid"]), int(row["matches"]), float(row["hydrofob"]))


def plot_top10(df_matches: pd.DataFrame, out_path: Path) -> None:
    """
    Plot a bar chart for the TOP-10 proteins by 'matches'.
    Additionally, annotate the bar that has the maximum 'hydrofob' within TOP-10.

    We avoid seaborn (the assignment typically expects matplotlib only).
    """
    if df_matches.empty:
        print("[INFO] Nothing to plot (no matches).")
        return

    # Take TOP-10 by matches (then by hydrofob for stable ordering)
    top = df_matches.sort_values(
        by=["matches", "hydrofob"], ascending=[False, False]
    ).head(10)

    # Find the index (within 'top') of the row with max hydrofob
    idx_max_h = top["hydrofob"].idxmax()
    max_h_row = top.loc[idx_max_h]

    # Build the bar chart
    plt.figure(figsize=(12, 6))
    x_labels = top["protid"].astype(str).tolist()
    heights = top["matches"].tolist()
    bars = plt.bar(range(len(top)), heights)

    # Annotate bar with max hydrofob (add a text label above the bar)
    max_pos = top.index.get_loc(idx_max_h)  # position inside [0..len(top)-1]
    plt.text(
        x=max_pos,
        y=heights[max_pos] + max(1, 0.03 * max(heights)),
        s=f"max hydrofob: {max_h_row['hydrofob']:.2f}",
        ha="center",
        va="bottom",
        fontsize=9,
        rotation=0,
    )

    # Set axis labels and title
    plt.xticks(range(len(top)), x_labels, rotation=45, ha="right")
    plt.xlabel("Protein ID (protid)")
    plt.ylabel("Matches (count of pattern occurrences)")
    plt.title("Top-10 proteins by matches (serial)")

    plt.tight_layout()
    plt.savefig(out_path)
    plt.close()
    print(f"[INFO] Chart saved to: {out_path}")


# ---------- Main script ----------

def main() -> None:
    # 1) Resolve working paths
    #    We assume the script is executed with working directory pointing to LAB2.
    #    If not, you can change base_dir to Path(__file__).parent.
    base_dir = Path(".").resolve()
    csv_path = base_dir / "proteins.csv"
    chart_path = base_dir / "top10_matches.png"

    # 2) Load dataset
    df = load_dataset(csv_path)

    # 3) Ask user for the pattern and normalize to uppercase
    pattern = input("Enter pattern to search (will be converted to UPPERCASE): ").strip().upper()
    if not pattern:
        sys.exit("[ERROR] Empty pattern is not allowed.")

    # 4) Measure time for the matching phase
    t0 = time.perf_counter()

    # 5) Compute overlapping matches for each sequence
    #    We create a new column 'matches' with the counts.
    df["matches"] = df["sequence"].apply(lambda s: count_overlapping(s, pattern))

    # 6) Keep only rows where matches > 0 for charting and winner selection
    df_hits = df.loc[df["matches"] > 0, ["protid", "hydrofob", "matches"]].copy()

    elapsed = time.perf_counter() - t0

    # 7) Print runtime
    print(f"[TIME] Serial search finished in {elapsed:.3f} seconds.")

    # 8) Winner: max(matches), tie -> max(hydrofob)
    winner_protid, winner_matches, winner_h = pick_winner(df_hits)
    if winner_matches == 0:
        print("[RESULT] No matches found for the given pattern.")
    else:
        print(f"[RESULT] Winner protid: {winner_protid} "
              f"(matches={winner_matches}, hydrofob={winner_h:.2f})")

    # 9) Plot TOP-10 bar chart (if we have any matches)
    plot_top10(df_hits, chart_path)


if __name__ == "__main__":
    main()
